import type {
  Event,
  Announcement,
  Member,
  Department,
  LiveStream,
  Preaching,
  ChatMessage,
} from '@/entities'

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Service du Dimanche',
    description: 'Service principal du dimanche',
    start_date: new Date(2024, 0, 21).toISOString(),
    end_date: new Date(2024, 0, 21).toISOString(),
    location: 'Église Principale',
    event_type: 'culte',
    is_recurring: true,
    recurrence_pattern: 'hebdomadaire',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Étude Biblique',
    description: 'Étude approfondie des Écritures',
    start_date: new Date(2024, 0, 24).toISOString(),
    end_date: new Date(2024, 0, 24).toISOString(),
    location: 'Salle de Réunion',
    event_type: 'séminaire',
    is_recurring: true,
    recurrence_pattern: 'hebdomadaire',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Prière et Intercession',
    description: 'Temps de prière collectif',
    start_date: new Date(2024, 0, 28).toISOString(),
    end_date: new Date(2024, 0, 28).toISOString(),
    location: 'Chapelle',
    event_type: 'autre',
    is_recurring: true,
    recurrence_pattern: 'hebdomadaire',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Nouvelles du Ministère',
    content: 'Bienvenue sur notre plateforme de gestion d\'église',
    priority: 'urgente',
    target_audience: 'tous',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Événement Spécial',
    content: 'Rejoignez-nous pour un événement inoubliable',
    priority: 'importante',
    target_audience: 'membres',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockMembers: Member[] = [
  {
    id: '1',
    first_name: 'Obi',
    last_name: 'Louis',
    email: 'chapellerestauration57@gmail.com',
    phone: '+237 6 99 79 04 62',
    role: 'pastor',
    status: 'active',
    join_date: '2020-01-15',
    department_id: '1',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    first_name: 'Marie',
    last_name: 'Martin',
    email: 'marie@example.com',
    phone: '0605060708',
    role: 'leader',
    status: 'active',
    join_date: '2021-03-20',
    department_id: '2',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    first_name: 'Pierre',
    last_name: 'Bernard',
    email: 'pierre@example.com',
    phone: '0609101112',
    role: 'member',
    status: 'active',
    join_date: '2022-06-10',
    department_id: '1',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Intercession',
    description: 'Un ministère dédié à la prière et à la bataille spirituelle pour notre communauté.',
    leader_name: 'Obi Louis',
    icon: 'Flame',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Louange & Adoration',
    description: 'Conduire l\'assemblée dans la présence de Dieu par la musique et les chants.',
    leader_name: 'Marie Martin',
    icon: 'Music',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Jeunesse',
    description: 'Accompagner et équiper la jeune génération pour Christ.',
    leader_name: 'Pierre Bernard',
    icon: 'Users',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Femmes',
    description: 'Édifier et encourager les femmes dans leur marche avec Dieu.',
    leader_name: 'Obi Louis',
    icon: 'Heart',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Hommes',
    description: 'Former des hommes de Dieu, leaders dans leurs familles et la société.',
    leader_name: 'Marie Martin',
    icon: 'Shield',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Enfants',
    description: 'Enseigner les fondements de la foi aux plus jeunes.',
    leader_name: 'Pierre Bernard',
    icon: 'Baby',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Evangelisation',
    description: 'Ministère d\'évangélisation et d\'outreach pour partager la bonne nouvelle.',
    leader_name: 'Obi Louis',
    icon: 'HeartHandshake',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockLiveStreams: LiveStream[] = [
  {
    id: '1',
    title: 'Service en Direct - Dimanche',
    description: 'Service principal du dimanche avec louange et prédication',
    youtube_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    is_live: true,
    start_time: new Date().toISOString(),
    viewers_count: 1247,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    stream_id: '1',
    user_name: 'Marie K.',
    message: 'Merveilleux message ce matin!',
    created_at: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: '2',
    stream_id: '1',
    user_name: 'Jean P.',
    message: 'Gloire à Dieu pour cette parole!',
    created_at: new Date(Date.now() - 45000).toISOString(),
  },
  {
    id: '3',
    stream_id: '1',
    user_name: 'Sarah M.',
    message: 'Je suis bénie par cet enseignement.',
    created_at: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: '4',
    stream_id: '1',
    user_name: 'Pierre D.',
    message: 'Que Dieu soit loué!',
    created_at: new Date(Date.now() - 15000).toISOString(),
  },
  {
    id: '5',
    stream_id: '1',
    user_name: 'Amélie C.',
    message: 'Amen! Continue à bénir!',
    created_at: new Date(Date.now() - 5000).toISOString(),
  },
]

export const mockPreachings: Preaching[] = [
  {
    id: '1',
    title: 'La Foi en Action',
    description: 'Découvrez comment manifester votre foi au quotidien',
    preacher: 'Pasteur Jean Dupont',
    date: '2024-01-14',
    media_type: 'video',
    media_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '45',
    views_count: 234,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'L\'Amour du Prochain',
    description: 'Comprendre et pratiquer l\'amour chrétien',
    preacher: 'Pasteure Marie Martin',
    date: '2024-01-07',
    media_type: 'video',
    media_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    duration: '60',
    views_count: 189,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock API delay simulator
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))
