import type {
  Event,
  Announcement,
  Member,
  Department,
  LiveStream,
  Preaching,
} from '@/entities'

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Service du Dimanche',
    description: 'Service principal du dimanche',
    date: new Date(2024, 0, 21).toISOString(),
    time: '09:00',
    location: 'Église Principale',
    category: 'service',
    speaker: 'Pasteur Jean',
    capacity: 500,
    registered: 300,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Étude Biblique',
    description: 'Étude approfondie des Écritures',
    date: new Date(2024, 0, 24).toISOString(),
    time: '19:00',
    location: 'Salle de Réunion',
    category: 'study',
    speaker: 'Pasteur Marie',
    capacity: 100,
    registered: 75,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Prière et Intercession',
    description: 'Temps de prière collectif',
    date: new Date(2024, 0, 28).toISOString(),
    time: '18:00',
    location: 'Chapelle',
    category: 'prayer',
    speaker: 'Équipe de Prière',
    capacity: 50,
    registered: 40,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Nouvelles du Ministère',
    content: 'Bienvenue sur notre plateforme de gestion d\'église',
    author: 'Pasteur Principal',
    priority: 'high',
    audience: 'all',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Événement Spécial',
    content: 'Rejoignez-nous pour un événement inoubliable',
    author: 'Équipe Événements',
    priority: 'medium',
    audience: 'members',
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockMembers: Member[] = [
  {
    id: '1',
    first_name: 'Jean',
    last_name: 'Dupont',
    email: 'jean@example.com',
    phone: '0601020304',
    role: 'pastor',
    status: 'active',
    join_date: '2020-01-15',
    department_id: '1',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    first_name: 'Marie',
    last_name: 'Martin',
    email: 'marie@example.com',
    phone: '0605060708',
    role: 'leader',
    status: 'active',
    join_date: '2021-03-20',
    department_id: '2',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    first_name: 'Pierre',
    last_name: 'Bernard',
    email: 'pierre@example.com',
    phone: '0609101112',
    role: 'member',
    status: 'active',
    join_date: '2022-06-10',
    department_id: '1',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Culte et Louange',
    description: 'Département responsable de la musique et des cultes',
    leader_id: '1',
    member_count: 25,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Jeunesse',
    description: 'Ministère pour les jeunes de 13 à 25 ans',
    leader_id: '2',
    member_count: 40,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Intercession',
    description: 'Équipe de prière et d\'intercession',
    leader_id: '3',
    member_count: 15,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockLiveStreams: LiveStream[] = [
  {
    id: '1',
    title: 'Service en Direct - Dimanche',
    url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    status: 'scheduled',
    start_time: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
    viewers_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockPreachings: Preaching[] = [
  {
    id: '1',
    title: 'La Foi en Action',
    description: 'Découvrez comment manifester votre foi au quotidien',
    speaker: 'Pasteur Jean Dupont',
    date: '2024-01-14',
    type: 'sermon',
    duration: 45,
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    audio_url: 'https://example.com/audio.mp3',
    views: 234,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'L\'Amour du Prochain',
    description: 'Comprendre et pratiquer l\'amour chrétien',
    speaker: 'Pasteure Marie Martin',
    date: '2024-01-07',
    type: 'teaching',
    duration: 60,
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    audio_url: 'https://example.com/audio2.mp3',
    views: 189,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// Mock API delay simulator
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))
